/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Dashboard;

/**
 *
 * @author MK
 */
public class Initial_Internal_Frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Init
     */
    public Initial_Internal_Frame() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Descr_1 = new javax.swing.JLabel();
        Descr_2 = new javax.swing.JLabel();
        Descr_3 = new javax.swing.JLabel();
        Descr_4 = new javax.swing.JLabel();
        Gest_Empl = new javax.swing.JLabel();
        Gest_Prod = new javax.swing.JLabel();
        Gest_Prov = new javax.swing.JLabel();
        Gest_Client = new javax.swing.JLabel();
        Fact = new javax.swing.JLabel();
        Report = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1030, 740));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1030, 740));

        Welcome.setBackground(new java.awt.Color(0, 0, 0));
        Welcome.setFont(new java.awt.Font("Roboto Medium", 0, 78)); // NOI18N
        Welcome.setForeground(new java.awt.Color(71, 13, 188));
        Welcome.setText("Bienvenido");

        Descr_1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_1.setForeground(new java.awt.Color(0, 0, 0));
        Descr_1.setText("Sistema de Gestion de Restaurante. Controla,");

        Descr_2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_2.setForeground(new java.awt.Color(0, 0, 0));
        Descr_2.setText("administre y venda de forma eficiente y simple");

        Descr_3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_3.setForeground(new java.awt.Color(0, 0, 0));
        Descr_3.setText("Este sistema le permitira mejorar el control de forma detallada y consisa de su negocio.");

        Descr_4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_4.setForeground(new java.awt.Color(0, 0, 0));
        Descr_4.setText("Podrá acceder a las diversas herramientas para sus necesidades especificas, tales:");

        Gest_Empl.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Gest_Empl.setForeground(new java.awt.Color(0, 0, 0));
        Gest_Empl.setText("• Gestion de Empleados.");

        Gest_Prod.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Gest_Prod.setForeground(new java.awt.Color(0, 0, 0));
        Gest_Prod.setText("• Gestion de Productos.");

        Gest_Prov.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Gest_Prov.setForeground(new java.awt.Color(0, 0, 0));
        Gest_Prov.setText("• Gestion de Proveedores.");

        Gest_Client.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Gest_Client.setForeground(new java.awt.Color(0, 0, 0));
        Gest_Client.setText("• Gestion de Clientes.");

        Fact.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Fact.setForeground(new java.awt.Color(0, 0, 0));
        Fact.setText("• Facturación.");

        Report.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Report.setForeground(new java.awt.Color(0, 0, 0));
        Report.setText("• Reportes.");

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rest.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Welcome)
                            .addComponent(Descr_1)
                            .addComponent(Descr_2)
                            .addComponent(Descr_3)
                            .addComponent(Descr_4)
                            .addComponent(Gest_Empl)
                            .addComponent(Gest_Prod))
                        .addGap(30, 30, 30)
                        .addComponent(Icon))
                    .addComponent(Gest_Prov)
                    .addComponent(Gest_Client)
                    .addComponent(Fact)
                    .addComponent(Report)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Welcome)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Descr_1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Descr_2)))
                        .addGap(18, 18, 18)
                        .addComponent(Descr_3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Descr_4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Gest_Empl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Gest_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Icon)))
                .addGap(20, 20, 20)
                .addComponent(Gest_Prov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Gest_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Fact, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descr_1;
    private javax.swing.JLabel Descr_2;
    private javax.swing.JLabel Descr_3;
    private javax.swing.JLabel Descr_4;
    private javax.swing.JLabel Fact;
    private javax.swing.JLabel Gest_Client;
    private javax.swing.JLabel Gest_Empl;
    private javax.swing.JLabel Gest_Prod;
    private javax.swing.JLabel Gest_Prov;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Report;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
