/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Producto;

/**
 *
 * @author tonit
 * @reviewer MK
 */

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ProductoView extends javax.swing.JInternalFrame {

    private ProductoController controller = new ProductoController();
    private JPanel[] paneles;
    String[] columnas = {
            "ID", "Producto", "Categoria", "Precio", "Disponibilidad","Stock"
    };
    DefaultTableModel modelo = new DefaultTableModel(null, columnas);
    
    public ProductoView() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        comboCategoria.setEditable(true);
        tblProducto.setModel(modelo);
        tblProducto.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        
            cargarCategorias();
            cargarProductos();
            cleanCampos();
            
// <editor-fold defaultstate="collapsed" desc="Configuraciones de Botones">
    paneles = new JPanel[] { btn_add, btn_search, btn_update, btn_delete, btn_clear, btn_showall }; 
    Color colorNormal = new Color(71,13,188);  
    Color colorHover = new Color(115,67,210);

        for (JPanel panel : paneles) {
            panel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                    panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                    panel.setBackground(colorHover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                    panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                    panel.setBackground(colorNormal);
            }
            });

        }// </editor-fold>
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        jSeparator6 = new javax.swing.JSeparator();
        btn_add = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_update = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_search = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_showall = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        comboCategoria = new javax.swing.JComboBox<>();
        comboEstado = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(1030, 740));
        setMinimumSize(new java.awt.Dimension(1030, 740));
        setPreferredSize(new java.awt.Dimension(1030, 740));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1018, 704));
        jPanel1.setMinimumSize(new java.awt.Dimension(1018, 704));
        jPanel1.setPreferredSize(new java.awt.Dimension(1018, 704));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Estado:");

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Stock:");

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Producto:");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Categoria:");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Precio:");

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(204, 204, 204));
        txtId.setMaximumSize(new java.awt.Dimension(250, 26));
        txtId.setMinimumSize(new java.awt.Dimension(250, 26));
        txtId.setName(""); // NOI18N
        txtId.setPreferredSize(new java.awt.Dimension(250, 26));

        txtProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtProducto.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(204, 204, 204));
        txtProducto.setMaximumSize(new java.awt.Dimension(250, 26));
        txtProducto.setMinimumSize(new java.awt.Dimension(250, 26));
        txtProducto.setName(""); // NOI18N
        txtProducto.setPreferredSize(new java.awt.Dimension(250, 26));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(204, 204, 204));
        txtPrecio.setMaximumSize(new java.awt.Dimension(250, 26));
        txtPrecio.setMinimumSize(new java.awt.Dimension(250, 26));
        txtPrecio.setName(""); // NOI18N
        txtPrecio.setPreferredSize(new java.awt.Dimension(250, 26));

        txtStock.setBackground(new java.awt.Color(255, 255, 255));
        txtStock.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtStock.setForeground(new java.awt.Color(204, 204, 204));
        txtStock.setMaximumSize(new java.awt.Dimension(250, 26));
        txtStock.setMinimumSize(new java.awt.Dimension(250, 26));
        txtStock.setName(""); // NOI18N
        txtStock.setPreferredSize(new java.awt.Dimension(250, 26));

        tblProducto.setBackground(new java.awt.Color(255, 255, 255));
        tblProducto.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        tblProducto.setForeground(new java.awt.Color(204, 204, 204));
        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Marca", "Precio", "Descripcion", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tblProducto);

        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_add.setBackground(new java.awt.Color(71, 13, 188));
        btn_add.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_add.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_add.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Agregar");

        javax.swing.GroupLayout btn_addLayout = new javax.swing.GroupLayout(btn_add);
        btn_add.setLayout(btn_addLayout);
        btn_addLayout.setHorizontalGroup(
            btn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7))
        );
        btn_addLayout.setVerticalGroup(
            btn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel7))
        );

        btn_update.setBackground(new java.awt.Color(71, 13, 188));
        btn_update.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_update.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_update.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Actualizar");

        javax.swing.GroupLayout btn_updateLayout = new javax.swing.GroupLayout(btn_update);
        btn_update.setLayout(btn_updateLayout);
        btn_updateLayout.setHorizontalGroup(
            btn_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_updateLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8))
        );
        btn_updateLayout.setVerticalGroup(
            btn_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_updateLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8))
        );

        btn_search.setBackground(new java.awt.Color(71, 13, 188));
        btn_search.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_search.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_search.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Buscar");

        javax.swing.GroupLayout btn_searchLayout = new javax.swing.GroupLayout(btn_search);
        btn_search.setLayout(btn_searchLayout);
        btn_searchLayout.setHorizontalGroup(
            btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_searchLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel9))
        );
        btn_searchLayout.setVerticalGroup(
            btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_searchLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel9))
        );

        btn_delete.setBackground(new java.awt.Color(71, 13, 188));
        btn_delete.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_delete.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_delete.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Eliminar");

        javax.swing.GroupLayout btn_deleteLayout = new javax.swing.GroupLayout(btn_delete);
        btn_delete.setLayout(btn_deleteLayout);
        btn_deleteLayout.setHorizontalGroup(
            btn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_deleteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel10))
        );
        btn_deleteLayout.setVerticalGroup(
            btn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_deleteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel10))
        );

        btn_clear.setBackground(new java.awt.Color(71, 13, 188));
        btn_clear.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_clear.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_clear.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Limpiar");

        javax.swing.GroupLayout btn_clearLayout = new javax.swing.GroupLayout(btn_clear);
        btn_clear.setLayout(btn_clearLayout);
        btn_clearLayout.setHorizontalGroup(
            btn_clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_clearLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel11))
        );
        btn_clearLayout.setVerticalGroup(
            btn_clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_clearLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11))
        );

        btn_showall.setBackground(new java.awt.Color(71, 13, 188));
        btn_showall.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_showall.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_showall.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_showall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showallMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mostrar todos");

        javax.swing.GroupLayout btn_showallLayout = new javax.swing.GroupLayout(btn_showall);
        btn_showall.setLayout(btn_showallLayout);
        btn_showallLayout.setHorizontalGroup(
            btn_showallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_showallLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12))
        );
        btn_showallLayout.setVerticalGroup(
            btn_showallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_showallLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel12))
        );

        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator7.setMaximumSize(new java.awt.Dimension(250, 10));
        jSeparator7.setMinimumSize(new java.awt.Dimension(250, 10));
        jSeparator7.setPreferredSize(new java.awt.Dimension(250, 10));

        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator8.setMaximumSize(new java.awt.Dimension(250, 10));
        jSeparator8.setMinimumSize(new java.awt.Dimension(250, 10));
        jSeparator8.setPreferredSize(new java.awt.Dimension(250, 10));

        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator9.setMaximumSize(new java.awt.Dimension(250, 10));
        jSeparator9.setMinimumSize(new java.awt.Dimension(250, 10));
        jSeparator9.setPreferredSize(new java.awt.Dimension(250, 10));

        jSeparator10.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator10.setMaximumSize(new java.awt.Dimension(250, 10));
        jSeparator10.setMinimumSize(new java.awt.Dimension(250, 10));
        jSeparator10.setPreferredSize(new java.awt.Dimension(250, 10));

        jSeparator11.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator11.setMaximumSize(new java.awt.Dimension(250, 10));
        jSeparator11.setMinimumSize(new java.awt.Dimension(250, 10));
        jSeparator11.setPreferredSize(new java.awt.Dimension(250, 10));

        jSeparator12.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator12.setMaximumSize(new java.awt.Dimension(250, 10));
        jSeparator12.setMinimumSize(new java.awt.Dimension(250, 10));
        jSeparator12.setPreferredSize(new java.awt.Dimension(250, 10));

        comboCategoria.setBackground(new java.awt.Color(255, 255, 255));
        comboCategoria.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        comboCategoria.setForeground(new java.awt.Color(204, 204, 204));
        comboCategoria.setBorder(null);
        comboCategoria.setMaximumSize(new java.awt.Dimension(250, 26));
        comboCategoria.setMinimumSize(new java.awt.Dimension(250, 26));
        comboCategoria.setPreferredSize(new java.awt.Dimension(250, 26));

        comboEstado.setBackground(new java.awt.Color(255, 255, 255));
        comboEstado.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        comboEstado.setForeground(new java.awt.Color(204, 204, 204));
        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        comboEstado.setBorder(null);
        comboEstado.setMaximumSize(new java.awt.Dimension(250, 26));
        comboEstado.setMinimumSize(new java.awt.Dimension(250, 26));
        comboEstado.setPreferredSize(new java.awt.Dimension(250, 26));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_showall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jLabel6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_showall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseClicked
    ProductoModel e = new ProductoModel();
    
    e.setProducto(txtProducto.getText());
    e.setCategoria(comboCategoria.getSelectedItem().toString());
    
    try {
        e.setPrecio(Double.parseDouble(txtPrecio.getText()));
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El Precio debe ser un número válido", "Error de validación", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    e.setEstado(comboEstado.getSelectedItem().toString().equals("Activo"));

    try {
        e.setStock(Integer.parseInt(txtStock.getText()));
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El Stock debe ser un número válido", "Error de validación", JOptionPane.ERROR_MESSAGE);
        return;
    }



    if (ProductoController.crear(e)) {
        JOptionPane.showMessageDialog(this, "Producto creado");
    }
        cargarCategorias();
        cargarProductos();
    }//GEN-LAST:event_btn_addMouseClicked

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked
    int fila = tblProducto.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un Producto de la tabla para actualizar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ProductoModel e = new ProductoModel();

    // Suponiendo que la primera columna del JTable contiene el ID
    int id = Integer.parseInt(tblProducto.getValueAt(fila, 0).toString());
    e.setId(id);
    
    e.setProducto(txtProducto.getText());
    e.setCategoria(comboCategoria.getSelectedItem().toString());
    
    try {
        e.setPrecio(Double.parseDouble(txtPrecio.getText()));
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El Precio debe ser un número válido", "Error de validación", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    e.setEstado(comboEstado.getSelectedItem().toString().equals("Activo"));

    try {
        e.setStock(Integer.parseInt(txtStock.getText()));
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El Stock debe ser un número válido", "Error de validación", JOptionPane.ERROR_MESSAGE);
        return;
    }


    if (ProductoController.actualizar(e)) {
        JOptionPane.showMessageDialog(this, "Producto actualizado");
        cargarCategorias();
        cargarProductos();
    }
    }//GEN-LAST:event_btn_updateMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
    if (txtId.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Debes ingresar un ID");
    return;
    }
    int id = Integer.parseInt(txtId.getText());
    ProductoModel e = ProductoController.buscar(id);
    modelo.setRowCount(0);
    if (e != null) {
        modelo.addRow(new Object[]{
            e.getId(), e.getProducto(), e.getCategoria(), e.getPrecio(),
            e.isEstado() ? "Activo" : "Inactivo",e.getStock()
        });
    } else {
        JOptionPane.showMessageDialog(this, "Producto no encontrado");
    }
    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
    int fila = tblProducto.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un Producto");
        return;
    }

    int id = Integer.parseInt(tblProducto.getValueAt(fila, 0).toString());
    int confirmar = JOptionPane.showConfirmDialog(this, "¿Eliminar ID: " + id + "?", "Confirmar", JOptionPane.YES_NO_OPTION);

    if (confirmar == JOptionPane.YES_OPTION) {
        if (ProductoController.eliminar(id)) {
            JOptionPane.showMessageDialog(this, "Empleado eliminado");
            cargarProductos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar");
        }
    }
    cargarCategorias();
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        cargarCategorias();
        cargarProductos();
        cleanCampos();
    }//GEN-LAST:event_btn_clearMouseClicked

    private void btn_showallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showallMouseClicked
    modelo = (DefaultTableModel) tblProducto.getModel();
    modelo.setRowCount(0);

    for (ProductoModel e : ProductoController.obtenerTodos()) {
        Object[] fila = {
            e.getId(), 
            e.getProducto(), 
            e.getCategoria(),
            e.getPrecio(),
            e.isEstado() ? "Activo" : "Inactivo",
            e.getStock()
        };
        modelo.addRow(fila);
    }
    }//GEN-LAST:event_btn_showallMouseClicked

private void cleanCampos() {
    txtId.setText("");
    txtProducto.setText("");
    comboCategoria.setSelectedItem("");
    txtPrecio.setText("");
    comboEstado.setSelectedItem("");
    txtStock.setText("");
}

private void cargarProductos() {
    modelo.setRowCount(0);
    List<ProductoModel> lista = ProductoController.obtenerTodos();
    for (ProductoModel e : lista) {
        modelo.addRow(new Object[]{
            e.getId(), e.getProducto(), e.getCategoria(), e.getPrecio(),
            e.isEstado() ? "Activo" : "Inactivo",e.getStock()
        });
    }
}

private void cargarCategorias() {
    comboCategoria.removeAllItems();

    List<String> cargos = ProductoController.obtenerCargos();
    for (String cargo : cargos) {
        comboCategoria.addItem(cargo);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_add;
    private javax.swing.JPanel btn_clear;
    private javax.swing.JPanel btn_delete;
    private javax.swing.JPanel btn_search;
    private javax.swing.JPanel btn_showall;
    private javax.swing.JPanel btn_update;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
