/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Usuario;

/**
 *
 * @author MK
 */


import java.awt.Color;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class UsuarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioView
     */
    
    private final JPanel[] paneles;
    String[] columnas = {
            "ID", "Usuario", "Password", "Rol", "Direccion", "Email"
        };
    DefaultTableModel modelo = new DefaultTableModel(null, columnas);
    public UsuarioView() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        ComboRol.setEditable(true);
        tblUsuario.setModel(modelo);
        tblUsuario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        
            cargarRoles();
            cargarUsuarios();
            cleanCampos();
        
// <editor-fold defaultstate="collapsed" desc="Configuraciones de Botones">
    paneles = new JPanel[] { btn_add, btn_search, btn_update, btn_delete, btn_clear, btn_showall }; 
    Color colorNormal = new Color(71,13,188);  
    Color colorHover = new Color(115,67,210);

        for (JPanel panel : paneles) {
            panel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                    panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                    panel.setBackground(colorHover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                    panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                    panel.setBackground(colorNormal);
            }
            });

        }// </editor-fold>
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        btn_add = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_update = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_search = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_showall = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        ComboRol = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(1032, 746));
        setMinimumSize(new java.awt.Dimension(1032, 746));
        setPreferredSize(new java.awt.Dimension(1032, 746));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setForeground(new java.awt.Color(255, 255, 255));

        btn_add.setBackground(new java.awt.Color(71, 13, 188));
        btn_add.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_add.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_add.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar");

        javax.swing.GroupLayout btn_addLayout = new javax.swing.GroupLayout(btn_add);
        btn_add.setLayout(btn_addLayout);
        btn_addLayout.setHorizontalGroup(
            btn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1))
        );
        btn_addLayout.setVerticalGroup(
            btn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1))
        );

        btn_update.setBackground(new java.awt.Color(71, 13, 188));
        btn_update.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_update.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_update.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Actualizar");

        javax.swing.GroupLayout btn_updateLayout = new javax.swing.GroupLayout(btn_update);
        btn_update.setLayout(btn_updateLayout);
        btn_updateLayout.setHorizontalGroup(
            btn_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_updateLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8))
        );
        btn_updateLayout.setVerticalGroup(
            btn_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_updateLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8))
        );

        btn_search.setBackground(new java.awt.Color(71, 13, 188));
        btn_search.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_search.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_search.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Buscar");

        javax.swing.GroupLayout btn_searchLayout = new javax.swing.GroupLayout(btn_search);
        btn_search.setLayout(btn_searchLayout);
        btn_searchLayout.setHorizontalGroup(
            btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_searchLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel9))
        );
        btn_searchLayout.setVerticalGroup(
            btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_searchLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel9))
        );

        btn_delete.setBackground(new java.awt.Color(71, 13, 188));
        btn_delete.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_delete.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_delete.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Eliminar");

        javax.swing.GroupLayout btn_deleteLayout = new javax.swing.GroupLayout(btn_delete);
        btn_delete.setLayout(btn_deleteLayout);
        btn_deleteLayout.setHorizontalGroup(
            btn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_deleteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel10))
        );
        btn_deleteLayout.setVerticalGroup(
            btn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_deleteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel10))
        );

        btn_showall.setBackground(new java.awt.Color(71, 13, 188));
        btn_showall.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_showall.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_showall.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_showall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showallMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mostrar todos");

        javax.swing.GroupLayout btn_showallLayout = new javax.swing.GroupLayout(btn_showall);
        btn_showall.setLayout(btn_showallLayout);
        btn_showallLayout.setHorizontalGroup(
            btn_showallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_showallLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12))
        );
        btn_showallLayout.setVerticalGroup(
            btn_showallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_showallLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel12))
        );

        btn_clear.setBackground(new java.awt.Color(71, 13, 188));
        btn_clear.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_clear.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_clear.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Limpiar");

        javax.swing.GroupLayout btn_clearLayout = new javax.swing.GroupLayout(btn_clear);
        btn_clear.setLayout(btn_clearLayout);
        btn_clearLayout.setHorizontalGroup(
            btn_clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_clearLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel11))
        );
        btn_clearLayout.setVerticalGroup(
            btn_clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_clearLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11))
        );

        tblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tblUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        tblUsuario.setForeground(new java.awt.Color(204, 204, 204));
        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Password", "Rol", "Direccion", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblUsuario);

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Usuario:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(110, 15));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(110, 15));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Rol:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel4.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel4.setPreferredSize(new java.awt.Dimension(110, 15));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Email:");
        jLabel5.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel5.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel5.setPreferredSize(new java.awt.Dimension(110, 15));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Password:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel6.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel6.setPreferredSize(new java.awt.Dimension(110, 15));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Direccion:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel7.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel7.setPreferredSize(new java.awt.Dimension(110, 15));

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setForeground(new java.awt.Color(204, 204, 204));
        txtId.setBorder(null);
        txtId.setMaximumSize(new java.awt.Dimension(300, 24));
        txtId.setMinimumSize(new java.awt.Dimension(300, 24));
        txtId.setPreferredSize(new java.awt.Dimension(300, 24));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setBorder(null);
        txtUsuario.setMaximumSize(new java.awt.Dimension(300, 24));
        txtUsuario.setMinimumSize(new java.awt.Dimension(300, 24));
        txtUsuario.setPreferredSize(new java.awt.Dimension(300, 24));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setBorder(null);
        txtPassword.setMaximumSize(new java.awt.Dimension(300, 24));
        txtPassword.setMinimumSize(new java.awt.Dimension(300, 24));
        txtPassword.setPreferredSize(new java.awt.Dimension(300, 24));

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setForeground(new java.awt.Color(204, 204, 204));
        txtDireccion.setBorder(null);
        txtDireccion.setMaximumSize(new java.awt.Dimension(300, 24));
        txtDireccion.setMinimumSize(new java.awt.Dimension(300, 24));
        txtDireccion.setPreferredSize(new java.awt.Dimension(300, 24));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setBorder(null);
        txtEmail.setMaximumSize(new java.awt.Dimension(300, 24));
        txtEmail.setMinimumSize(new java.awt.Dimension(300, 24));
        txtEmail.setPreferredSize(new java.awt.Dimension(300, 24));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator1.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator2.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator3.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator4.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator4.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator5.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator5.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator6.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator6.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator6.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        ComboRol.setBackground(new java.awt.Color(255, 255, 255));
        ComboRol.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        ComboRol.setForeground(new java.awt.Color(204, 204, 204));
        ComboRol.setMaximumSize(new java.awt.Dimension(300, 24));
        ComboRol.setMinimumSize(new java.awt.Dimension(300, 24));
        ComboRol.setPreferredSize(new java.awt.Dimension(300, 24));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_showall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(ComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_showall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseClicked
    UsuarioModel e = new UsuarioModel();
    
    e.setUsuario(txtUsuario.getText());
    e.setPassword(txtPassword.getText());
    e.setRol(ComboRol.getSelectedItem().toString());
    e.setDireccion(txtDireccion.getText());
    e.setEmail(txtEmail.getText());

    if (UsuarioController.crear(e)) {
        JOptionPane.showMessageDialog(this, "Usuario creado");
    }
    cargarRoles();
    cargarUsuarios();
    }//GEN-LAST:event_btn_addMouseClicked

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked
    int fila = tblUsuario.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un Usuario de la tabla para actualizar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    UsuarioModel e = new UsuarioModel();

    // Suponiendo que la primera columna del JTable contiene el ID
    int id = Integer.parseInt(tblUsuario.getValueAt(fila, 0).toString());
    e.setId(id);
    
    e.setUsuario(txtUsuario.getText());
    e.setPassword(txtPassword.getText());
    e.setRol(ComboRol.getSelectedItem().toString());
    e.setDireccion(txtDireccion.getText());
    e.setEmail(txtEmail.getText());

    if (UsuarioController.actualizar(e)) {
        JOptionPane.showMessageDialog(this, "Usuario actualizado");
    cargarRoles();
    cargarUsuarios();
    }
    }//GEN-LAST:event_btn_updateMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
                                  
    if (txtId.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debes ingresar un ID");
        return;
    }

    int id = Integer.parseInt(txtId.getText());
    UsuarioModel e = UsuarioController.buscar(id);
    modelo.setRowCount(0);

    if (e != null) {
        modelo.addRow(new Object[]{
            e.getId(), 
            e.getUsuario(), 
            e.getPassword(), 
            e.getRol(), 
            e.getDireccion(), 
            e.getEmail()
        });

        // Ocultar columna "email" (columna 9)
        tblUsuario.getColumnModel().getColumn(2).setMinWidth(0);
        tblUsuario.getColumnModel().getColumn(2).setMaxWidth(0);
        tblUsuario.getColumnModel().getColumn(2).setWidth(0);

    } else {
        JOptionPane.showMessageDialog(this, "Usuario no encontrado");
    }

    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
    int fila = tblUsuario.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un Usuario");
        return;
    }

    int id = Integer.parseInt(tblUsuario.getValueAt(fila, 0).toString());
    int confirmar = JOptionPane.showConfirmDialog(this, "¿Eliminar ID: " + id + "?", "Confirmar", JOptionPane.YES_NO_OPTION);

    if (confirmar == JOptionPane.YES_OPTION) {
        if (UsuarioController.eliminar(id)) {
            JOptionPane.showMessageDialog(this, "Usuario eliminado");
            cargarUsuarios();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar");
        }
    }
    cargarRoles();
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void btn_showallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showallMouseClicked
    modelo = (DefaultTableModel) tblUsuario.getModel();
    modelo.setRowCount(0); // Limpia tabla

    for (UsuarioModel e : UsuarioController.obtenerTodos()) {
        Object[] fila = {
            e.getId(),
            e.getUsuario(),
            e.getPassword(),
            e.getRol(),
            e.getDireccion(),
            e.getEmail()
        };
        modelo.addRow(fila);
    }

    // Ocultar la columna de contraseña (índice 2 en este arreglo)
    tblUsuario.getColumnModel().getColumn(2).setMinWidth(0);
    tblUsuario.getColumnModel().getColumn(2).setMaxWidth(0);
    tblUsuario.getColumnModel().getColumn(2).setWidth(0);
    }//GEN-LAST:event_btn_showallMouseClicked

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        cargarRoles();
        cargarUsuarios();
        cleanCampos();
    }//GEN-LAST:event_btn_clearMouseClicked

private void cleanCampos() {
    txtId.setText("");
    txtUsuario.setText("");
    txtPassword.setText("");
    ComboRol.setSelectedItem("");
    txtDireccion.setText("");
    txtEmail.setText("");
}

private void cargarUsuarios() {
    DefaultTableModel model = (DefaultTableModel) tblUsuario.getModel();
    model.setRowCount(0);

    for (UsuarioModel e : UsuarioDAO.getAll()) {
        model.addRow(new Object[]{
            e.getId(),
            e.getPassword(),
            e.getUsuario(),
            e.getRol(),
            e.getDireccion(),
            e.getEmail()
        });
    }

    // Ocultar la columna de contraseña (index 1)
    tblUsuario.getColumnModel().getColumn(2).setMinWidth(0);
    tblUsuario.getColumnModel().getColumn(2).setMaxWidth(0);
    tblUsuario.getColumnModel().getColumn(2).setWidth(0);
}

private void cargarRoles() {
    ComboRol.removeAllItems();

    List<String> cargos = UsuarioController.obtenerRoles();
    for (String cargo : cargos) {
        ComboRol.addItem(cargo);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JComboBox<String> ComboRol;
    private javax.swing.JPanel btn_add;
    private javax.swing.JPanel btn_clear;
    private javax.swing.JPanel btn_delete;
    private javax.swing.JPanel btn_search;
    private javax.swing.JPanel btn_showall;
    private javax.swing.JPanel btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
