/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package Proveedor;

/**
 *
 * @author tonit
 * @author MK
 * 
 */

import java.awt.Color;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ProveedorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProveedores
     */

    private final JPanel[] paneles;
    String[] columnas = {
            "Nit", "Proveedor", "Telefono_Empresa", "Contacto", "Telefono_Contacto", "Direccion"
    };
    DefaultTableModel modelo = new DefaultTableModel(null, columnas);

    public ProveedorView() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        tblProveedor.setModel(modelo);
        tblProveedor.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        cargarProveedor();
        cleanCampos();

        // <editor-fold defaultstate="collapsed" desc="Configuraciones de Botones">
        paneles = new JPanel[] { btn_add, btn_search, btn_update, btn_delete, btn_clear, btn_showall };
        Color colorNormal = new Color(71, 13, 188);
        Color colorHover = new Color(115, 67, 210);

        for (JPanel panel : paneles) {
            panel.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                    panel.setBackground(colorHover);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                    panel.setBackground(colorNormal);
                }
            });

        } // </editor-fold>

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelEmp = new javax.swing.JTextField();
        txtTelCont = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btn_add = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_update = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_search = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_showall = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        Background.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Proveedor:");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NIT:");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contacto:");

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Direccion:");

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Telefono Empresa:");

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Telefono Contacto:");

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setForeground(new java.awt.Color(204, 204, 204));
        txtDireccion.setBorder(null);
        txtDireccion.setMaximumSize(new java.awt.Dimension(300, 24));
        txtDireccion.setMinimumSize(new java.awt.Dimension(300, 24));
        txtDireccion.setPreferredSize(new java.awt.Dimension(300, 24));

        txtTelEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtTelEmp.setForeground(new java.awt.Color(204, 204, 204));
        txtTelEmp.setBorder(null);
        txtTelEmp.setMaximumSize(new java.awt.Dimension(300, 24));
        txtTelEmp.setMinimumSize(new java.awt.Dimension(300, 24));
        txtTelEmp.setPreferredSize(new java.awt.Dimension(300, 24));

        txtTelCont.setBackground(new java.awt.Color(255, 255, 255));
        txtTelCont.setForeground(new java.awt.Color(204, 204, 204));
        txtTelCont.setBorder(null);
        txtTelCont.setMaximumSize(new java.awt.Dimension(300, 24));
        txtTelCont.setMinimumSize(new java.awt.Dimension(300, 24));
        txtTelCont.setPreferredSize(new java.awt.Dimension(300, 24));

        txtNit.setBackground(new java.awt.Color(255, 255, 255));
        txtNit.setForeground(new java.awt.Color(204, 204, 204));
        txtNit.setBorder(null);
        txtNit.setMaximumSize(new java.awt.Dimension(300, 24));
        txtNit.setMinimumSize(new java.awt.Dimension(300, 24));
        txtNit.setPreferredSize(new java.awt.Dimension(300, 24));

        txtProveedor.setBackground(new java.awt.Color(255, 255, 255));
        txtProveedor.setForeground(new java.awt.Color(204, 204, 204));
        txtProveedor.setBorder(null);
        txtProveedor.setMaximumSize(new java.awt.Dimension(300, 24));
        txtProveedor.setMinimumSize(new java.awt.Dimension(300, 24));
        txtProveedor.setPreferredSize(new java.awt.Dimension(300, 24));

        txtContacto.setBackground(new java.awt.Color(255, 255, 255));
        txtContacto.setForeground(new java.awt.Color(204, 204, 204));
        txtContacto.setBorder(null);
        txtContacto.setMaximumSize(new java.awt.Dimension(300, 24));
        txtContacto.setMinimumSize(new java.awt.Dimension(300, 24));
        txtContacto.setPreferredSize(new java.awt.Dimension(300, 24));

        tblProveedor.setBackground(new java.awt.Color(255, 255, 255));
        tblProveedor.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        tblProveedor.setForeground(new java.awt.Color(204, 204, 204));
        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIT", "Proveedor", "Telefono Empresa", "Contacto", "Telefono Contacto", "Direccion"
            }
        ));
        jScrollPane1.setViewportView(tblProveedor);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator1.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator2.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator3.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator4.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator4.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator5.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator5.setPreferredSize(new java.awt.Dimension(300, 10));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator6.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator6.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator6.setPreferredSize(new java.awt.Dimension(300, 10));

        btn_add.setBackground(new java.awt.Color(71, 13, 188));
        btn_add.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_add.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_add.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar");

        javax.swing.GroupLayout btn_addLayout = new javax.swing.GroupLayout(btn_add);
        btn_add.setLayout(btn_addLayout);
        btn_addLayout.setHorizontalGroup(
            btn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1))
        );
        btn_addLayout.setVerticalGroup(
            btn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1))
        );

        btn_update.setBackground(new java.awt.Color(71, 13, 188));
        btn_update.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_update.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_update.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Actualizar");

        javax.swing.GroupLayout btn_updateLayout = new javax.swing.GroupLayout(btn_update);
        btn_update.setLayout(btn_updateLayout);
        btn_updateLayout.setHorizontalGroup(
            btn_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_updateLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8))
        );
        btn_updateLayout.setVerticalGroup(
            btn_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_updateLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8))
        );

        btn_search.setBackground(new java.awt.Color(71, 13, 188));
        btn_search.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_search.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_search.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Buscar");

        javax.swing.GroupLayout btn_searchLayout = new javax.swing.GroupLayout(btn_search);
        btn_search.setLayout(btn_searchLayout);
        btn_searchLayout.setHorizontalGroup(
            btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_searchLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel9))
        );
        btn_searchLayout.setVerticalGroup(
            btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_searchLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel9))
        );

        btn_delete.setBackground(new java.awt.Color(71, 13, 188));
        btn_delete.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_delete.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_delete.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Eliminar");

        javax.swing.GroupLayout btn_deleteLayout = new javax.swing.GroupLayout(btn_delete);
        btn_delete.setLayout(btn_deleteLayout);
        btn_deleteLayout.setHorizontalGroup(
            btn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_deleteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel10))
        );
        btn_deleteLayout.setVerticalGroup(
            btn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_deleteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel10))
        );

        btn_clear.setBackground(new java.awt.Color(71, 13, 188));
        btn_clear.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_clear.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_clear.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Limpiar");

        javax.swing.GroupLayout btn_clearLayout = new javax.swing.GroupLayout(btn_clear);
        btn_clear.setLayout(btn_clearLayout);
        btn_clearLayout.setHorizontalGroup(
            btn_clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_clearLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel11))
        );
        btn_clearLayout.setVerticalGroup(
            btn_clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_clearLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11))
        );

        btn_showall.setBackground(new java.awt.Color(71, 13, 188));
        btn_showall.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_showall.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_showall.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_showall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showallMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mostrar todos");

        javax.swing.GroupLayout btn_showallLayout = new javax.swing.GroupLayout(btn_showall);
        btn_showall.setLayout(btn_showallLayout);
        btn_showallLayout.setHorizontalGroup(
            btn_showallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_showallLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12))
        );
        btn_showallLayout.setVerticalGroup(
            btn_showallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_showallLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel12))
        );

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel4))
                    .addComponent(jLabel7)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5)))
                .addGap(10, 10, 10)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_showall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addComponent(jLabel5))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtTelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtTelCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_showall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_addMouseClicked
        ProveedorModel e = new ProveedorModel();

        e.setNit(txtNit.getText());
        e.setProveedor(txtProveedor.getText());
        e.setTelef_empre(txtTelEmp.getText());
        e.setContacto(txtContacto.getText());
        e.setTelef_contacto(txtTelCont.getText());
        e.setDireccion(txtDireccion.getText());

        if (ProveedorController.crear(e)) {
            JOptionPane.showMessageDialog(this, "Proveedor creado");
        }
        cargarProveedor();
    }

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_updateMouseClicked
        int fila = tblProveedor.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Proveedor de la tabla para actualizar", "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        ProveedorModel e = new ProveedorModel();

        // Suponiendo que la primera columna del JTable contiene el ID
        String nit = tblProveedor.getValueAt(fila, 0).toString();
        e.setNit(nit);

        e.setProveedor(txtProveedor.getText());
        e.setTelef_empre(txtTelEmp.getText());
        e.setContacto(txtContacto.getText());
        e.setTelef_contacto(txtTelCont.getText());
        e.setDireccion(txtContacto.getText());

        if (ProveedorController.actualizar(e)) {
            JOptionPane.showMessageDialog(this, "Proveedor actualizado");
            cargarProveedor();
        }
    }// GEN-LAST:event_btn_updateMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_searchMouseClicked
        if (txtNit.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un NIT");
            return;
        }
        String nit = txtNit.getText();
        ProveedorModel p = ProveedorController.buscar(nit);
        modelo.setRowCount(0);
        if (p != null) {
            modelo.addRow(new Object[] {
                    p.getNit(),
                    p.getProveedor(),
                    p.getTelef_empre(),
                    p.getContacto(),
                    p.getTelef_contacto(),
                    p.getDireccion()
            });
        } else {
            JOptionPane.showMessageDialog(this, "Proveedor no encontrado");
        }
    }

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_deleteMouseClicked
        int fila = tblProveedor.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un Proveedor");
            return;
        }

        String nit = tblProveedor.getValueAt(fila, 0).toString();
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Eliminar NIT: " + nit + "?", "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {
            if (ProveedorController.eliminar(nit)) {
                JOptionPane.showMessageDialog(this, "Proveedor eliminado");
                cargarProveedor();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
        }
    }// GEN-LAST:event_btn_deleteMouseClicked

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_clearMouseClicked
        cargarProveedor();
        cleanCampos();
    }// GEN-LAST:event_btn_clearMouseClicked

    private void btn_showallMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_showallMouseClicked
        modelo = (DefaultTableModel) tblProveedor.getModel();
        modelo.setRowCount(0); // Limpia tabla

        for (ProveedorModel p : ProveedorController.obtenerTodos()) {
            Object[] fila = {
                    p.getNit(),
                    p.getProveedor(),
                    p.getTelef_empre(),
                    p.getContacto(),
                    p.getTelef_contacto(),
                    p.getDireccion()

            };
            modelo.addRow(fila);
        }
    }// GEN-LAST:event_btn_showallMouseClicked

    /*
     * private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {
     * 
     * }
     */

    private void cleanCampos() {
        txtNit.setText("");
        txtProveedor.setText("");
        txtTelEmp.setText("");
        txtContacto.setText("");
        txtTelCont.setText("");
        txtDireccion.setText("");
    }

    private void cargarProveedor() {
        modelo.setRowCount(0);
        List<ProveedorModel> lista = ProveedorController.obtenerTodos();
        for (ProveedorModel p : lista) {
            modelo.addRow(new Object[] {
                    p.getNit(),
                    p.getProveedor(),
                    p.getTelef_empre(),
                    p.getContacto(),
                    p.getContacto(),
                    p.getDireccion()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel btn_add;
    private javax.swing.JPanel btn_clear;
    private javax.swing.JPanel btn_delete;
    private javax.swing.JPanel btn_search;
    private javax.swing.JPanel btn_showall;
    private javax.swing.JPanel btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtTelCont;
    private javax.swing.JTextField txtTelEmp;
    // End of variables declaration//GEN-END:variables
}
